#!/bin/bash

#Variables
test_env='./test/test_env'

git -C $test_env/clone1 notes append -m "push notes test"

#move origin out of master branch to allow push
git -C $test_env/origin checkout -b temp --quiet

# python3 git-mytest.py -C $test_env/clone1 -p