#!/bin/bash

#Variables
test_env='./test/test_env'

#move origin out of master branch to allow push
git -C $test_env/origin checkout -b temp --quiet

git -C $test_env/origin notes append -m "origin note"

git -C $test_env/clone1 notes append -m "clone note"
# python3 git-mytest.py -C $test_env/clone1 -f