#!/bin/bash

#Variables
test_env='./test/test_env'
commit_sha1=$(egrep "[0-9a-f]{40}" <(git -C $test_env/origin log) | tail -n 1 | awk "{ print \$2 }")


git -C $test_env/origin notes append -m "note1"
git -C $test_env/origin notes append -m "note2"
git -C $test_env/origin notes append -m "note3"
git -C $test_env/origin notes append -m "note4"
git -C $test_env/origin notes append -m "note5"
git -C $test_env/origin notes append -m "note6"
git -C $test_env/origin notes append -m "note7"

git -C $test_env/origin notes append -m "1note" $commit_sha1
git -C $test_env/origin notes append -m "2note" $commit_sha1
git -C $test_env/origin notes append -m "3note" $commit_sha1
git -C $test_env/origin notes append -m "4note" $commit_sha1
git -C $test_env/origin notes append -m "5note" $commit_sha1
git -C $test_env/origin notes append -m "6note" $commit_sha1
git -C $test_env/origin notes append -m "7note" $commit_sha1



# python3 git-mytest.py -C $test_env/clone1 -f